### ISSUE TITLE
Custom Ack timeout

### ISSUE THREAD

**Issue by alexellis** [openfaas/nats-queue-worker#10]
## Description

Ack time-out appears to be set to 30 seconds. This means async jobs should complete within 30 seconds or they will be retried.

## Workarounds

The synchronous timeout can be upped and used instead.  

## Solution

We should look at options, but we can:

* Ack early and continue ( functions/queue-worker:ack_early )
* Make the timeout custom

Thanks @blu3gui7ar for notifying.

**Comment by blu3gui7ar** [comment]
Currently, Nats provide 'run at least once' semantic for tasks. 

If infrastructure intends to provide more execution semantics, such as ' run once and only once', the Ack behavior should be enhanced.

Another option is to leave it to the task. In that case,  more metadata from Nats, such as 'redeliver' and 'task id', should be exposed to task (through http header?).

An enhanced queue-worker with common execution semantics support would be preferable to me.

**Comment by alexellis** [comment]
This is now customisable
