### ISSUE TITLE
Move the queue-worker to Go modules

### ISSUE THREAD

**Issue by alexellis** [openfaas/nats-queue-worker#101]
## Task

Move the queue-worker to Go modules

Dep is now deprecated.

I would suggest that a previous contributor to openfaas takes this.

I'd be most comfortable if @matthiashanel had time to look into it given his recent contributions and understanding of the NATS work upstream.

**Comment by matthiashanel** [comment]
@alexellis do you have a time line for this in mind? I'd aim for Friday next week or the Monday after.

**Comment by alexellis** [comment]
That timeline would work, thank you 👍

**Comment by matthiashanel** [comment]
Assign it to me then

**Comment by alexellis** [comment]
Given we are almost a year on, I took this.

@matthiashanel feel free to check out the results to see if they are as you would have done it.
