### ISSUE TITLE
Make NATS Streaming message input/response optional

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/nats-queue-worker#11]
Because `func_queue-worker` writes output to the log, it is visible when you run `docker service logs func_queue-worker`.

This means that if you are returning binary data from your function, the logs will be useless.

I think that debug logs of output data should be surpressed by default (similar to `write_debug = false`).

**Comment by alexellis** [comment]
I think I did this.. but it's an optional flag  because it's extremely useful to have the message body printed out for debugging.

**Comment by alexellis** [comment]
@ericstoekl can we get an update please?

**Comment by alexellis** [comment]
While in the code I'd like to see the several env-parsing statements execrated to a new Config struct.

```
if val, exists := os.LookupEnv("faas_nats_address"); exists {
		natsAddress = val
	}

	if val, exists := os.LookupEnv("faas_gateway_address"); exists {
		gatewayAddress = val
	}

	if val, exists := os.LookupEnv("faas_function_suffix"); exists {
		functionSuffix = val
	}

	if val, exists := os.LookupEnv("faas_print_body"); exists {
		debugPrintBody = val == "1" || val == "true"
	}
```

This should work in a similar way to `faas`/`faas-netes` or one of the other projects that reads env-vars into a config struct.

**Comment by ericstoekl** [comment]
So we want to do something similar to how this works? https://github.com/openfaas/faas/blob/d3d320dc33262fdc63c00440f8b800219849ac3d/gateway/types/readconfig.go#L56

I think I see what needs to be done here, just need to test it out and submit a PR

**Comment by burtonr** [comment]
Derek close: merged
