### ISSUE TITLE
Why this does not use jetstream ?

### ISSUE THREAD

**Issue by gedw99** [openfaas/nats-queue-worker#120]
Sorry to ask a question but is there a reason this does not use jetstream . Seems to use the old Stan which is approaching End of Life

**Comment by alexellis** [comment]
Hey @gedw99 thanks for your interest

We've already thought about this well ahead of time:

https://www.openfaas.com/blog/jetstream-for-openfaas/

Alex

**Comment by alexellis** [comment]
/set title: Is JetStream available for OpenFaaS?

**Comment by alexellis** [comment]
What's your interest / use-case @gedw99 ?

**Comment by gedw99** [comment]
Well I use nats and would like to use open Fass. The way I see it is that there’s a ton of cool features in nats jetstream that can make serverless architecture even better than the current limitations.

don’t get me wrong. Fassd is out standing but it can be better with jet stream which I am guessing your aware of too
