### ISSUE TITLE
ghcr missing tag 0.13.0

### ISSUE THREAD

**Issue by bluehawk27** [openfaas/nats-queue-worker#121]
Previous image tags for ghcr should remain available for those of us that cannot upgrade all of our clusters in a reasonable timeframe. ghcr.io/openfaas/queue-worker:0.13.0 is not pullable for me. While I know the image is old.... It should remain available.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi @bluehawk27 update to the latest version of the image or Helm chart, that'll resolve your issue.

See also: https://www.openfaas.com/blog/time-to-update/

Alex
