### ISSUE TITLE
Support scale_from_zero

### ISSUE THREAD

**Issue by alexellis** [openfaas/nats-queue-worker#32]
## Expected Behaviour

In the gateway, when a function is invoked which has zero replicas, it will request that the function is scaled up and then block the HTTP request until the function is ready. The queue-worker should mirror this behaviour.

## Current Behaviour

The queue-worker calls functions directly over HTTP, so if a function (deployment) has 0/0 replicas it will return an error - HTTP 502 or similar.

Direct function call: https://github.com/openfaas/nats-queue-worker/blob/master/main.go#L119

## Possible Solution

Option 1:

Make use of the gateway code for maintaining a list of services and replicas, then call the existing gateway API to scale. Code can be re-used from exported packages.

Option 2:

Have the queue-worker always call the gateway instead of the functions directly. Adds latency and means the async timeout will be reduced to the sync route timeout value.

Option 3:

Have the gateway scale deployments to minReplicas whenever it gets an async work-item queued.

## Steps to Reproduce (for bugs)

1. Enable scale from zero
2. Deploy figlet from store
3. Scale figlet to zero with kubectl/docker
4. Invoke figlet via gateway and see it scale
5. Repeat process, but this time invoke via async route.

## Context

scale_from_zero is an important feature for multi-tenant environments

**Comment by LucasRoesler** [comment]
I like two things about about Option 2 

1.  it solves scale up and scale down by keeping all of the logic and required state information in a single place (the gateway) _and_ it does this without a lot of changes
2. it make for a very predictable flow both for how requests get to the function.  The same for how a function scales. 

Overall, I like the consistency it brings. 

If a message is already waiting in a queue, is the latency from a hop to the gateway really a bottleneck/concern?

**Comment by alexellis** [comment]
> If a message is already waiting in a queue, is the latency from a hop to the gateway really a bottleneck/concern?

It could be for very high throughput. It depends on the use-case.

At the moment there is the ability to set up multiple timeout values so you can have a longer run-time for work on the async queue vs work entering via the gateway.

Gateway:

function timeout must be lower than GW timeout

GW tends to face the public, so a shorter timeout is recommended

Queue worker:

Queue worker timeout || function timeout

If the queue-worker timeout is at least as big as the function timeout then it will run for that duration. This is independent of the gateway timeout value.

I.e. you could set the GW to 5 seconds, the function to 5 mins the queue-worker to 10 mins.

In the GW synchronous path the max timeout is 5 seconds, if the function invocation overruns it will be killed.

In the async example the function can run for up to 10 mins before the invocation is killed.

So by going via the gateway we would be harmonizing the timeout values and encouraging people to up the maximum timeout value on their gateway.

**Comment by stefanprodan** [comment]
I would go with option 3 to avoid a roundtrip and keep the worker code simple.

**Comment by alexellis** [comment]
OK so we have a vote for 2 + 3.

In scenario 2 we have a chatty interface where the work comes into NATS via the gateway's async endpoint, then goes via the queue/stream and back to the gateway on the synchronous endpoint.
What about the current behavior where you can have a different async timeout than sync timeout? 
GW - set low to prevent abuse - i.e. 2-3 seconds. Async set to 5 minutes.

In scenario 3 the gateway will scale the service as soon as the work is taken in - but users will not expect to go from ms to queue an item to 1-3s to queue an item, so we can't do it synchronously. And if we don't do it synchronously then the NATS queue-worker will probably hit the endpoint too early and fail. How do we resolve that?

**Comment by burtonr** [comment]
I'll put a vote in for option 3. 

I think the latency will become a problem especially as I know there are already some issues with managed K8s services (specifically Azure) and adding additional latency, and network traffic will only make the problem worse, or more prevalent. Also, that timeout scenario sounds like it would lead to a lot of confusion.

For resolving the issue about NATS queue-worker accessing the endpoint too early, would it be possible to add a quick re-try as a fail-safe? I'm thinking retry 2-3 times in 1-2 seconds (maybe more) before it fails. Perhaps that could be some configuration option. Also, since this is for async function execution, is it really a problem if it takes a little longer during the initial scale-from-0?

**Comment by LucasRoesler** [comment]
Is latency on asynchronous calls a big concern? I understand the issue for synchronous calls. 

Having said that, the worker should have an expiration back off anyway. I think option 3 is also a d cent way to go

**Comment by ewilde** [comment]
Happy to work on this if no one else has started on it. Need this to go live with faas-fargate

**Comment by alexellis** [comment]
Thanks Ed. Just need to work out which approach is most appropriate. 

I am leaning towards vendoring out the scaling code from the gateway component to faas-dcos and running it here and in the queue worker too.

**Comment by alexellis** [comment]
I'm working on this currently and expect to have it released some time over the next few days. The gateway piece is done and the nats-queue-worker piece is done but undergoing more testing.

**Comment by alexellis** [comment]
I don't remember where the branch is for this code. 

On retrospect I'm still torn on the way the queue-worker invokes functions directly. It should probably invoke via the synchronous endpoint of the gateway. It would be good to get some feedback from end-users who are using asynchronous functions as to how important it is to have a separate timeout from the gateway timeout for the asynchronous function invocation.

**Comment by alexellis** [comment]
@matipan

**Comment by matipan** [comment]
In my case it does not matter if the timeouts are different. But I see why people would want to have that. They could be using the functions for some sorts of batch processing or something and having the high timeout for async calls but not sync might be useful.

In my opinion I would still go for option 3 and continue to call the functions directly or have the gateway provide an endpoint(accessible only inside the cluster) to call the functions but with the async timeout

**Comment by anmtan** [comment]
Hello, I am new to openfaas and exploring async function scale from zero. Just wondering if there is any timeline for this feature to be implemented @alexellis. Thanks.

**Comment by alexellis** [comment]
@anmtan what's your use-case? Are you aware that functions specifically need to opt-in to using scale to zero? i.e. it doesn't affect you unless you scale the "async" function to zero.

**Comment by anmtan** [comment]
Yes, I am aware of that. I tried calling the function synchronously, and it did scale to 1 from zero. Our use case is batch processing for a long running job. It may take seconds or even a minute to finish running the function. When I scaled this async function to zero and invoked this function asynchronously, it did not scale to 1 from zero.

**Comment by alexellis** [comment]
> When I scaled this async function to zero and invoked this function asynchronously, it did not scale to 1 from zero.

That is correct, as per the issue definition.

Have you considered for the time-being, making those important functions scale to zero (i.e. don't add the `com.openfaas.scale.zero: true` label?

**Comment by alekar** [comment]
It might be valuable to have different timeouts for synchronous and asynchronous workloads. A lot of asynchronous work can have longer timeouts if it's running on a 'best effort' SLA. 

Any thoughts about having the queue worker call the provider? It might be a compelling option: it is possible to colocate a 'read-only' provider with the queue worker. Then there is no cost of a network hop, and there is clean separation of concerns. The provider invokes a function. The cloud worker knows how to manage the async interaction.

Secondly, having short synchronous timeouts are easier for gateway redeployments, given one has to drain active requests while redeploying. This might preclude invoking async workflows via the gateway. Draining is not really an issue for the queue worker because it reads from a work queue, which has an at least once semantic. This seems to map pretty well to the queue worker semantic, that some jobs might rerun.

This does present a challenge: how to wire the metrics and scaling. I am thinking the provider, or the queue worker is going to have to post metrics to the gateway. Or prometheus needs to poll the queue worker/ provider.

**Comment by alexellis** [comment]
Thanks for your thoughts.

**Comment by alexellis** [comment]
I've read the thread over again and I think option 3 seems to have the most votes.

To summarise, it would work like this:

Currently the gateway sales up functions which are at 0/0 replicas when it receives a synchronous call.

When this work is complete then the asynchronous endpoint of the gateway will do the same.

I think we could hit a race condition where a function is reporting ready > 0/0 replicas but that the function pod is not fully ready and then the queued work would fail.

A second failure point may be if the function is scaled to zero whilst there is a backlog of items in the NATS Streaming queue. This may happen if the queue worker crashes and restarts - if that restart takes > "scale duration" then the function will be scaled down and the queued up requests won't be on a path that scales functions > 0/0 so all requests would fail.

I may be wrong, I have been before and so that's why I'm trying to get some input from the community here. I think we should offer a feature-flag to invoke functions via the gateway's synchronous endpoint and then monitor user-feedback. (this is "Option 2")

The side-effect from option 2 is that we could then remove the custom metrics endpoints from the gateway which existed to allow the queue-worker to post back details after invoking functions. In this topology the queue-worker becomes more similar to the way our connector-sdk works.

Pros:

* we have fewer timeouts to configure
* less code paths in the queue-worker
* "scale from zero" in a consistent manner to the gateway, in one predictable place
* ingesting asynchronous invocation requests doesn't incur the cost of scale from zero

Cons:

* we drop the ability to have a separate timeout for the asynchronous invocations (no end-users have commented about this, but it doesn't mean it won't break their setup)
* chatty Interface user -> GW -> NATS -> queue-worker -> GW -> function

**Comment by matipan** [comment]
> Regarding the gateway's synchronous timeout - this may be limited by the LoadBalancer or IngressController, in which case we may be able to have a higher single timeout on the gateway and configure our Cloud Ingress to restrict the "effective" synchronous timeout.

I did not take this into account. I believe I like option 2 better now. It's true that we could create a somewhat chatty interface, but I would rather have a chatty interface with a clear separation of concerns than the opposite.

**Comment by alexellis** [comment]
I'll have a look at this over the course of my flight.
