### ISSUE TITLE
Auth needed for gateway calls to /system/async-report

### ISSUE THREAD

**Issue by alexellis** [openfaas/nats-queue-worker#35]
## Expected Behaviour

The call to `/system/async-report` needs to be decorated with basic auth credentials.

## Current Behaviour

It is open which is why no changes were needed, but this is invalid because someone could discover the gateway and post false statistics to this endpoint.

## Possible Solution

- Update docker-compose/helm/yaml to add the basic auth username/password to this component
- Update the HTTP call to `/system/async-report`to pass those secrets

## Steps to Reproduce (for bugs)

1. Deploy OpenFaaS with auth
2. Post to `gateway:port/system/async-report`
3.
4.

## Context

Found whilst doing a deeper code review on the faas/server entrypoint

**Comment by viveksyngh** [comment]
Derek assign: me
