### ISSUE TITLE
Allow alternate port for gateway to invoke functions

### ISSUE THREAD

**Issue by acornies** [openfaas/nats-queue-worker#59]
## Expected Behaviour
When using OpenFaaS on Nomad I'd expect to be able to override the gateway port based on my configuration.

## Current Behaviour
The queue worker has a hard-coded value of :8080 as the gateway port. https://github.com/openfaas/nats-queue-worker/blob/master/main.go#L80

## Possible Solution
Allow the gateway port to be configurable or pass and use the information from the async request message itself.

## Context
I cannot setup the queue worker in my Nomad-based OpenFaaS environment since my gateway port is not listening on :8080 and there's no default overlay networking.

**Comment by alexellis** [comment]
@acornies is this still the case?

**Comment by acornies** [comment]
Yes: https://github.com/openfaas/nats-queue-worker/blob/master/main.go#L33

**Comment by alexellis** [comment]
I guess on K8s/Swarm, all gateway services listen on port `8080`. Is this a nomad thing?

**Comment by alexellis** [comment]
I'd accept a patch that included the port in the gateway address / configuration.

**Comment by acornies** [comment]
Will do! In short, yes. I've worked around it for now but would be nice to have it configurable for those not running overlay.

**Comment by alexellis** [comment]
Looks like @jonatasbaldin has picked this up now.
