### ISSUE TITLE
Custom headers and QueryString should be serialized and passed onto function.

### ISSUE THREAD

**Issue by alexellis** [openfaas/nats-queue-worker#6]
Custom headers such as `X-Forwarded-By` or query string values such as `?id=alex` should be passed onto the function when it is invoked by a queue worker. This also needs a related change in the gateway: https://github.com/openfaas/faas/issues/369

**Comment by alexellis** [comment]
A change would be required here to construct a URL - https://github.com/openfaas/nats-queue-worker/blob/master/queue-worker/main.go#L93

**Comment by johnmccabe** [comment]
@alexellis  this can be closed now, both #7 and openfaas/faas#369 are merged/closed.

**Comment by alexellis** [comment]
Derek close

**Comment by dungeonmaster18** [comment]
Derek: close

**Comment by alexellis** [comment]
Derek close
