### ISSUE TITLE
404 Asyc Doc Readme

### ISSUE THREAD

**Issue by kwojcicki** [openfaas/nats-queue-worker#64]
404 Linked in the README.md

https://github.com/openfaas/nats-queue-worker/blame/master/README.md#L9 (currently links https://github.com/openfaas/faas/blob/master/guide/asynchronous.md)

should probably be linking to https://docs.openfaas.com/reference/async/

**Comment by alexellis** [comment]
Thanks for your help. I would love a PR for this.

Please just make sure to `git commit --signoff` to avoid upsetting Derek 😄

**Comment by kwojcicki** [comment]
Fix up https://github.com/openfaas/nats-queue-worker/pull/65, managed to remember adding -s :laughing:

**Comment by alexellis** [comment]
Thank you :)
