### ISSUE TITLE
Provide original function name in callback

### ISSUE THREAD

**Issue by ewilde** [openfaas/nats-queue-worker#82]
The callback currently contains the following meta-data from the original invocation:

|Header | Description
-- | --
X-Call-Id | The original function call's tracing UUID
X-Duration-Seconds | Time taken in seconds to execute the original function call
X-Function-Status | HTTP status code returned by the original function call

I am proposing that we add the original function name as well

| Header | Description
-- | --
X-Function-Name | The original function name that was invoked

## Use case
With this extra piece of meta-data people can design their own back-off / retry / eventual consistency systems, without the need to modify any core OpenFaaS components

Consider this design now enabled by the extra field

![image](https://user-images.githubusercontent.com/329397/70561913-40b62000-1bf0-11ea-8a82-c418b863d794.png)

**Comment by alexellis** [comment]
I am fine with this.
