### ISSUE TITLE
Show built version and SHA on start-up

### ISSUE THREAD

**Issue by alexellis** [openfaas/nats-queue-worker#92]
Show built version and SHA on start-up

## Expected Behaviour

Users should be able to identify versions from logs

## Current Behaviour

You can inspect the Docker image

## Possible Solution

See the logs of faas-netes and use the same approach

## Steps to Reproduce (for bugs)

1. `arkade install openfaas`
2. `kubectl logs -n openfaas deploy/queue-worker`

## Context

Better consistency and logging.

**Comment by Amalkh5** [comment]
fixed by #93

**Comment by alexellis** [comment]
Thanks @Amalkh5
