### ISSUE TITLE
Remove durable config from the readme

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/nats-queue-worker#96]
## Context

In #95 the durable configuration was removed

https://github.com/openfaas/nats-queue-worker/pull/95/files#diff-3511d0be867c6e99793319238ebe2438L48

So we should remove this line from the README 

https://github.com/openfaas/nats-queue-worker/blame/master/README.md#L37

**Comment by alexellis** [comment]
@matthiashanel could you take this please?

**Comment by alexellis** [comment]
See also: https://github.com/openfaas/docs/issues/225
